import type { ControlTowerSection, ControlTowerSectionId } from "./types";

const capability = (title: string, description: string, owner: string, status: "live" | "configured" | "needs-backend" | "restricted" = "live") => ({ title, description, owner, status });

export const controlTowerSections: readonly ControlTowerSection[] = [
  { id: "overview", label: "Today", icon: "dashboard", readPermission: "content:read", commandLabel: "Today at SALORA", keywords: ["dashboard", "tasks", "alerts", "activity"], description: "A clear view of what needs your attention now.", capabilities: [capability("Operational brief", "Shows real system capability and pending operator work without invented business metrics.", "Operations")] },
  { id: "experience", label: "Experience", icon: "pages", readPermission: "content:read", commandLabel: "Edit experiences", keywords: ["homepage", "pages", "brand", "assets", "navigation", "mobile"], description: "Control how SALORA appears across the website, menu and mobile experience.", capabilities: [capability("Experience Studio", "Uses the production ExperiencePageV2 renderer, approved registry and safe presentation controls.", "Experience")] },
  { id: "menu", label: "Products", icon: "menu", readPermission: "catalog:read", commandLabel: "Manage products", keywords: ["products", "categories", "collections", "modifiers", "featured", "presentation"], description: "Manage products, prices, images, availability and publishing from one place.", capabilities: [capability("Product operations", "Reuses catalog APIs for bounded product and category management.", "Catalog")] },
  { id: "orders", label: "Orders", icon: "orders", readPermission: "order:read", commandLabel: "Open orders", keywords: ["active", "preparing", "ready", "history", "issues"], description: "Order queues, details and validated state transitions using the existing order domain.", capabilities: [capability("Order operations", "Reads bounded order pages and uses the current server-validated transition API.", "Operations")] },
  { id: "customers", label: "Customers", icon: "user", readPermission: "staff:read", commandLabel: "Open customers", keywords: ["directory", "profiles", "loyalty", "segments"], description: "Customer and loyalty operations exposed only where current permissions and domain services support them.", capabilities: [capability("Customer intelligence", "Reuses existing customer intelligence surfaces with least-privilege access.", "Customer Intelligence"), capability("Loyalty operations", "Only existing loyalty rules and protected award operations are exposed.", "Loyalty")] },
  { id: "marketing", label: "Marketing", icon: "brand", readPermission: "catalog:read", commandLabel: "Open marketing", keywords: ["campaigns", "promotions", "offers", "qr", "social"], description: "Promotions, offers and campaign content built on existing commercial services.", capabilities: [capability("Promotions and coupons", "Reuses existing bounded APIs; no direct table editor or arbitrary configuration writes.", "Marketing")] },
  { id: "ai", label: "AI", icon: "ai", readPermission: "catalog:read", commandLabel: "Open SALORA AI", keywords: ["assistant", "copy", "translation", "recommendations", "audit"], description: "Contextual, human-reviewed assistance for content, localization and experience quality.", capabilities: [capability("AI draft tools", "Suggestions remain review-only and can only be applied to a draft.", "AI Governance"), capability("Production authority", "AI has no publish permission and receives no secrets or unnecessary customer data.", "Security", "restricted")] },
  { id: "analytics", label: "Analytics", icon: "analytics", readPermission: "system:read", commandLabel: "Open analytics", keywords: ["products", "menu", "customers", "campaigns", "revenue"], description: "Links existing business and operational intelligence into a coherent workspace.", capabilities: [capability("Existing dashboards", "Reuses authoritative dashboards without fabricating unavailable metrics.", "Analytics")] },
  { id: "operations", label: "Operations", icon: "whatsapp", readPermission: "system:read", commandLabel: "Open operations", keywords: ["whatsapp", "runtime", "integrations", "diagnostics", "deployments"], description: "Operational status, WhatsApp, runtime governance and safe diagnostics without exposing topology or secrets.", capabilities: [capability("WhatsApp operations", "Reuses provider and message operations while keeping credentials server-only.", "Omnichannel"), capability("Runtime governance", "Shows safe operational abstractions and existing governance controls.", "SRE")] },
  { id: "settings", label: "Settings", icon: "settings", readPermission: "system:read", commandLabel: "Open settings", keywords: ["general", "brand", "languages", "users", "roles", "permissions", "audit", "integrations"], description: "Governed configuration, access and audit surfaces—not a generic database administration console.", capabilities: [capability("RBAC and audit", "Uses current roles, server permission checks and protected audit services.", "Security"), capability("Runtime configuration", "Existing typed, non-secret configuration remains server-controlled.", "Platform")] }
] as const;

export const controlTowerNavigationGroups = [
  { key: "overview", label: "Today", icon: "dashboard", sections: ["overview"] },
  { key: "catalog", label: "Products", icon: "menu", sections: ["menu"] },
  { key: "experience", label: "Experience", icon: "pages", sections: ["experience", "marketing"] },
  { key: "operations", label: "Operations", icon: "orders", sections: ["orders", "customers", "analytics", "ai", "operations", "settings"] }
] as const;

export const legacyControlTowerSectionAliases: Readonly<Record<string, ControlTowerSectionId>> = { executive: "overview", revenue: "analytics", inventory: "menu", loyalty: "customers", whatsapp: "operations", instagram: "marketing", notifications: "operations", content: "experience", "menu-authority": "menu", automation: "operations", integrations: "operations" };
export function findControlTowerSection(id?: string): ControlTowerSection { const canonicalId = id ? legacyControlTowerSectionAliases[id] ?? id : "overview"; const section = controlTowerSections.find((item) => item.id === canonicalId) ?? controlTowerSections[0]; if (!section) throw new Error("Control Tower registry must include Overview."); return section; }
export const validControlTowerSectionIds = controlTowerSections.map((section) => section.id) as ControlTowerSectionId[];
