import assert from "node:assert/strict";import fs from "node:fs";
const read=p=>fs.readFileSync(p,"utf8");
const join=read("apps/web/app/rewards/join/page.tsx"),rewards=read("apps/web/app/rewards/page.tsx"),repo=read("apps/web/lib/server/auth/prismaRepository.ts"),route=read("apps/web/app/api/auth/register/route.ts"),http=read("apps/web/lib/server/auth/http.ts"),service=read("apps/web/lib/server/auth/service.ts"),loyalty=read("packages/backend/src/domains/loyalty/persistence.ts"),migration=read("prisma/migrations/202609180005_harmony_customer_hardening/migration.sql"),schema=read("prisma/schema.prisma");
assert.match(join,/\/api\/auth\/register/);assert.match(join,/harmonyConsent:true/);assert.match(join,/minLength=\{12\}/);assert.match(join,/aria-live="assertive"/);
assert.match(rewards,/membershipCode/);assert.match(rewards,/كيف تكسب النقاط/);assert.match(rewards,/متاحة للاستبدال/);
assert.match(repo,/withPrismaAuthContextTx\(SYSTEM_AUTH_CONTEXT/);assert.match(repo,/customerProfile\.create/);assert.match(repo,/loyaltyAccount\.create/);assert.match(repo,/harmonyConsent\.create/);assert.match(repo,/WEB_REWARDS_JOIN/);
assert.match(http,/harmonyConsent: z\.literal\(true\)/);assert.match(http,/\.strict\(\)/);assert.match(http,/toLowerCase/);
assert.match(service,/policyCode: "HARMONY_V1"/);assert.match(route,/MAX_BODY_BYTES=8192/);assert.match(route,/sameOrigin/);assert.match(route,/Unable to create an account with the supplied details/);assert.doesNotMatch(route,/clientMeta/);
assert.match(loyalty,/idempotencyKey:\`welcome:\$\{input\.customerId\}\`/);assert.match(loyalty,/type:"BONUS"/);assert.match(loyalty,/harmony_consents/);assert.match(loyalty,/first eligible paid order/);
assert.match(migration,/harmony_consents/);assert.match(migration,/membership_code/);assert.match(migration,/ENABLE ROW LEVEL SECURITY/);assert.match(schema,/model HarmonyConsent/);assert.match(schema,/membershipCode/);
console.log("Harmony customer onboarding hardening checks passed.");