"use client";
import Link from "next/link"; import {useEffect,useState} from "react";
type Data={customer:{displayName:string|null;loyalty:null|{points:number;ledger:Array<{id:string;type:string;points:number;reason:string;createdAt:string}>;redemptions:Array<{id:string;reward:{name:string;pointsCost:number}}>}};rewards:Array<{id:string;code:string;name:string;pointsCost:number}>};
export default function RewardsPage(){
 const [data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(true),[status,setStatus]=useState<number|null>(null);
 useEffect(()=>{fetch("/api/rewards/me",{credentials:"include"}).then(async r=>{setStatus(r.status);if(r.ok)setData(await r.json())}).finally(()=>setLoading(false))},[]);
 if(loading)return <main className="grid min-h-screen place-items-center bg-[var(--background)] text-[var(--cream)]"><p>Harmony Rewards…</p></main>;
 if(status===401)return <main dir="rtl" className="grid min-h-screen place-items-center bg-[var(--background)] px-5 text-[var(--cream)]"><section className="w-full max-w-md rounded-3xl border border-[var(--border-gold)] bg-[var(--surface)] p-6 text-center"><p className="text-xs font-semibold tracking-[.2em] text-[var(--gold-soft)]">SALORA · HARMONY</p><h1 className="mt-3 text-3xl font-semibold">مكافآتك تنتظرك</h1><p className="mt-3 text-sm leading-7 text-[var(--muted)]">سجّل الدخول لعرض رصيدك ونقاطك ومكافآتك.</p><Link href="/login?next=/rewards" className="mt-6 flex min-h-12 items-center justify-center rounded-xl bg-[var(--cream)] font-semibold text-[var(--background)]">تسجيل الدخول</Link></section></main>;
 if(!data)return <main dir="rtl" className="grid min-h-screen place-items-center bg-[var(--background)] px-5 text-[var(--cream)]"><section className="text-center"><h1 className="text-2xl font-semibold">Harmony Rewards</h1><p className="mt-2 text-[var(--muted)]">لم يتم إنشاء ملف عميل لهذا الحساب بعد.</p></section></main>;
 const points=data.customer.loyalty?.points??0; const next=data.rewards.find(r=>r.pointsCost>points)??data.rewards[0]; const progress=next?Math.min(100,Math.round(points/Math.max(next.pointsCost,1)*100)):100;
 return <main dir="rtl" className="min-h-screen bg-[var(--background)] px-4 py-6 text-[var(--cream)] sm:px-6"><div className="mx-auto max-w-3xl">
  <header className="flex items-center justify-between"><div><p className="text-xs font-semibold tracking-[.2em] text-[var(--gold-soft)]">SALORA · HARMONY REWARDS</p><h1 className="mt-2 text-2xl font-semibold">أهلاً {data.customer.displayName||""}</h1></div><Link href="/menu" className="rounded-xl border border-[var(--border-subtle)] px-4 py-3 text-sm">المنيو</Link></header>
  <section className="mt-6 overflow-hidden rounded-3xl border border-[var(--border-gold)] bg-[linear-gradient(135deg,rgba(197,160,86,.15),rgba(255,255,255,.025))] p-6"><p className="text-sm text-[var(--muted)]">رصيد Harmony</p><div className="mt-2 flex items-end gap-2"><strong className="text-6xl text-[var(--gold-soft)]">{points}</strong><span className="pb-2 text-sm text-[var(--muted)]">نقطة</span></div>{next?<><div className="mt-6 h-2 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-[var(--gold-soft)]" style={{width:progress+"%"}}/></div><p className="mt-2 text-xs text-[var(--muted)]">متبقي {Math.max(0,next.pointsCost-points)} نقطة إلى {next.name}</p></>:null}</section>
  <section className="mt-8"><div className="flex items-end justify-between"><div><p className="text-xs text-[var(--gold-soft)]">REWARDS</p><h2 className="mt-1 text-xl font-semibold">المكافآت المتاحة</h2></div><span className="text-xs text-[var(--muted)]">{data.rewards.length} مكافأة</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{data.rewards.length?data.rewards.map(r=><article key={r.id} className="rounded-2xl border border-[var(--border-subtle)] bg-[var(--surface)] p-4"><div className="flex justify-between gap-3"><strong>{r.name}</strong><span className="shrink-0 text-sm text-[var(--gold-soft)]">{r.pointsCost} نقطة</span></div><p className="mt-3 text-xs text-[var(--muted)]">{points>=r.pointsCost?"مؤهل للاستبدال — اطلبها من فريق سالورا":"واصل جمع النقاط لفتح هذه المكافأة"}</p></article>):<div className="rounded-2xl border border-dashed border-[var(--border-subtle)] p-5 text-sm text-[var(--muted)]">سيتم عرض المكافآت هنا فور تفعيل كتالوج Harmony.</div>}</div></section>
  <section className="mt-8 pb-20"><p className="text-xs text-[var(--gold-soft)]">ACTIVITY</p><h2 className="mt-1 text-xl font-semibold">آخر حركات النقاط</h2><div className="mt-4 overflow-hidden rounded-2xl border border-[var(--border-subtle)]">{data.customer.loyalty?.ledger.length?data.customer.loyalty.ledger.map(e=><div key={e.id} className="flex items-center justify-between border-b border-[var(--border-subtle)] p-4 last:border-0"><div><strong className="text-sm">{e.reason}</strong><p className="mt-1 text-xs text-[var(--muted)]">{new Date(e.createdAt).toLocaleDateString("ar-OM")}</p></div><b className={e.points>=0?"text-[var(--gold-soft)]":""}>{e.points>0?"+":""}{e.points}</b></div>):<p className="p-5 text-sm text-[var(--muted)]">لا توجد حركات نقاط بعد.</p>}</div></section>
 </div></main>
}