"use client";

import { useEffect, useMemo, useState } from "react";
import { Eye, History, ImagePlus, MonitorSmartphone, Palette, Plus, RotateCcw, Save, Send, Trash2 } from "lucide-react";
import type { ExperienceBanner, ExperienceConfiguration, Product } from "@salora/types";
import { controlTowerGet, controlTowerPatch } from "@/lib/control-tower/client";
import { defaultExperienceConfiguration } from "@/lib/experience/config";
import { useControlTowerLocale } from "./ControlTowerLocale";

type Revision = { id: string; action: string; createdAt: string; actorId?: string; reason?: string };
type StudioPayload = { draft: ExperienceConfiguration; published: ExperienceConfiguration; draftVersion: number; publishedVersion: number; history: Revision[] };
type Tab = "menu" | "theme" | "banners" | "surfaces" | "history";

const fieldClass = "w-full rounded-xl border border-white/10 bg-black/35 px-3 py-2.5 text-sm text-[var(--cream)] outline-none focus:border-[var(--border-gold)]";

function Toggle({ checked, onChange, label }: { checked: boolean; onChange: (value: boolean) => void; label: string }) {
  return <label className="flex items-center justify-between gap-3 rounded-xl border border-white/10 bg-white/[0.035] px-3 py-3 text-sm text-[var(--muted)]"><span>{label}</span><button type="button" role="switch" aria-checked={checked} aria-label={label} onClick={() => onChange(!checked)} className={`relative h-6 w-11 rounded-full transition ${checked ? "bg-[var(--gold)]" : "bg-white/15"}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-black transition ${checked ? "start-6" : "start-1"}`} /></button></label>;
}

function TextField({ label, value, onChange, multiline = false }: { label: string; value: string; onChange: (value: string) => void; multiline?: boolean }) {
  return <label className="grid gap-2 text-sm text-[var(--muted)]"><span>{label}</span>{multiline ? <textarea value={value} onChange={(event) => onChange(event.target.value)} rows={3} className={fieldClass} /> : <input value={value} onChange={(event) => onChange(event.target.value)} className={fieldClass} />}</label>;
}

function Preview({ config, isArabic }: { config: ExperienceConfiguration; isArabic: boolean }) {
  const banner = config.banners.filter((item) => item.active && (item.placement === "menu" || item.placement === "both")).sort((a, b) => a.sortOrder - b.sortOrder)[0];
  const ratio = { landscape: "aspect-[16/10]", square: "aspect-square", portrait: "aspect-[4/5]" }[config.menu.cardRatio];
  const columns = { 2: "grid-cols-2", 3: "grid-cols-3", 4: "grid-cols-4" }[config.menu.columns];
  const font = { sans: "font-sans", serif: "font-serif", modern: "font-mono" }[config.theme.fontFamily];
  const style = { "--preview-primary": config.theme.primaryColor, "--preview-bg": config.theme.backgroundColor, "--preview-surface": config.theme.surfaceColor, "--preview-text": config.theme.textColor, "--preview-muted": config.theme.mutedColor, borderRadius: `${config.theme.borderRadius}px` } as React.CSSProperties;
  return <div dir={isArabic ? "rtl" : "ltr"} style={style} className={`overflow-hidden border border-white/10 bg-[var(--preview-bg)] text-[var(--preview-text)] shadow-2xl ${font}`}>
    <div className="flex items-center justify-between border-b border-white/10 px-4 py-3"><strong className="tracking-[0.22em]">SALORA</strong><span className="rounded-full bg-[var(--preview-primary)] px-3 py-1 text-xs text-black">{isArabic ? "اطلب" : "Order"}</span></div>
    {config.site.showAnnouncement ? <div className="bg-[var(--preview-primary)] px-3 py-2 text-center text-xs font-semibold text-black">{isArabic ? config.site.announcementAr : config.site.announcementEn}</div> : null}
    <div className="p-5">
      <h3 className="text-2xl font-bold">{isArabic ? config.site.heroTitleAr : config.site.heroTitleEn}</h3>
      <p className="mt-2 text-sm leading-6 text-[var(--preview-muted)]">{isArabic ? config.site.heroSubtitleAr : config.site.heroSubtitleEn}</p>
      {banner ? <div className="relative mt-4 overflow-hidden border border-white/10 bg-[var(--preview-surface)] p-4" style={{ borderRadius: `${Math.max(config.theme.borderRadius - 6, 0)}px`, backgroundImage: banner.imageUrl ? `linear-gradient(90deg, rgba(0,0,0,.82), rgba(0,0,0,.25)), url(${banner.imageUrl})` : undefined, backgroundSize: "cover" }}><strong>{isArabic ? banner.titleAr : banner.titleEn}</strong><p className="mt-1 text-xs text-[var(--preview-muted)]">{isArabic ? banner.subtitleAr : banner.subtitleEn}</p></div> : null}
      {config.menu.showSearch ? <div className="mt-4 rounded-xl border border-white/10 bg-[var(--preview-surface)] px-3 py-2 text-xs text-[var(--preview-muted)]">{isArabic ? "ابحث في المنيو" : "Search the menu"}</div> : null}
      <div className={`mt-4 grid gap-3 ${config.menu.layout === "list" ? "grid-cols-1" : columns}`}>
        {["لاتيه سالورا", "ماتشا مانجو", "سان سباستيان", "كولد برو"].slice(0, config.menu.layout === "list" ? 3 : 4).map((name, index) => <div key={name} className={`overflow-hidden border border-white/10 bg-[var(--preview-surface)] ${config.menu.layout === "list" ? "flex" : ""}`} style={{ borderRadius: `${Math.max(config.theme.borderRadius - 8, 0)}px` }}>{config.menu.showImages ? <div className={`${config.menu.layout === "list" ? "h-20 w-24" : ratio} bg-gradient-to-br from-[var(--preview-primary)]/40 to-black`} /> : null}<div className="p-3"><strong className="text-xs">{isArabic ? name : ["SALORA Latte", "Mango Matcha", "San Sebastian", "Cold Brew"][index]}</strong>{config.menu.showDescriptions ? <p className="mt-1 line-clamp-2 text-[0.65rem] text-[var(--preview-muted)]">{isArabic ? "وصف الصنف يظهر هنا" : "Product description appears here"}</p> : null}</div></div>)}
      </div>
    </div>
  </div>;
}

export function ExperienceDesignStudio() {
  const { isArabic } = useControlTowerLocale();
  const [tab, setTab] = useState<Tab>("menu");
  const [config, setConfig] = useState<ExperienceConfiguration>(defaultExperienceConfiguration);
  const [history, setHistory] = useState<Revision[]>([]);
  const [versions, setVersions] = useState({ draft: 0, published: 0 });
  const [status, setStatus] = useState<"loading" | "idle" | "saving" | "publishing" | "error">("loading");
  const [message, setMessage] = useState("");

  useEffect(() => { void (async () => { const result = await controlTowerGet<StudioPayload>("/api/control-tower/experience"); if (result.status === "success" && result.data) { setConfig(result.data.draft); setHistory(result.data.history); setVersions({ draft: result.data.draftVersion, published: result.data.publishedVersion }); setStatus("idle"); } else { setStatus("error"); setMessage(result.message ?? "Failed to load studio"); } })(); }, []);

  const update = <K extends keyof ExperienceConfiguration>(key: K, value: ExperienceConfiguration[K]) => setConfig((current) => ({ ...current, [key]: value }));
  const tabs = useMemo(() => [
    { id: "menu" as const, ar: "شكل المنيو", en: "Menu layout", icon: Eye },
    { id: "theme" as const, ar: "الثيم والهوية", en: "Theme", icon: Palette },
    { id: "banners" as const, ar: "البنرات", en: "Banners", icon: ImagePlus },
    { id: "surfaces" as const, ar: "الموقع والتطبيق", en: "Site & app", icon: MonitorSmartphone },
    { id: "history" as const, ar: "السجل والرجوع", en: "History", icon: History }
  ], []);

  async function submit(action: "save" | "publish") { setStatus(action === "save" ? "saving" : "publishing"); setMessage(""); const result = await controlTowerPatch<{ draftVersion: number; publishedVersion?: number }>("/api/control-tower/experience", { action, configuration: config }); if (result.status === "success") { setVersions((current) => ({ draft: result.data?.draftVersion ?? current.draft, published: result.data?.publishedVersion ?? current.published })); setMessage(isArabic ? (action === "publish" ? "تم النشر على المنيو والموقع وواجهة التطبيق." : "تم حفظ المسودة بأمان.") : (action === "publish" ? "Published to menu, site and app API." : "Draft saved safely.")); setStatus("idle"); } else { setStatus("error"); setMessage(result.message ?? "Save failed"); } }
  async function rollback(revisionId: string) { if (!window.confirm(isArabic ? "استرجاع هذه النسخة ونشرها؟" : "Restore and publish this revision?")) return; setStatus("publishing"); const result = await controlTowerPatch<{ configuration: ExperienceConfiguration }>("/api/control-tower/experience", { action: "rollback", revisionId }); if (result.status === "success" && result.data) { setConfig(result.data.configuration); setMessage(isArabic ? "تم استرجاع النسخة ونشرها." : "Revision restored and published."); setStatus("idle"); } else { setStatus("error"); setMessage(result.message ?? "Rollback failed"); } }
  function addBanner() { const banner: ExperienceBanner = { id: crypto.randomUUID(), titleAr: "عرض جديد", titleEn: "New offer", subtitleAr: "أضف وصف العرض", subtitleEn: "Add offer details", imageUrl: "", linkUrl: "/menu", placement: "both", active: true, sortOrder: config.banners.length }; update("banners", [...config.banners, banner]); }
  function updateBanner(id: string, change: Partial<ExperienceBanner>) { update("banners", config.banners.map((banner) => banner.id === id ? { ...banner, ...change } : banner)); }

  return <section className="salora-glass rounded-3xl p-4 sm:p-6">
    <div className="flex flex-col gap-4 border-b border-white/10 pb-5 xl:flex-row xl:items-center xl:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.22em] text-[var(--gold-soft)]">SALORA EXPERIENCE STUDIO</p><h2 className="mt-2 text-2xl font-semibold text-[var(--cream)]">{isArabic ? "استوديو تصميم التجربة دون برمجة" : "No-code Experience Design Studio"}</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-[var(--muted)]">{isArabic ? "تحكم موحد في شكل المنيو والثيم والبنرات والموقع والتطبيق، مع مسودة ونشر وسجل رجوع." : "One place for menu, theme, banners, site and app, with drafts, publishing and rollback."}</p></div><div className="flex flex-wrap gap-2"><span className="inline-flex items-center rounded-xl border border-white/10 px-3 py-2 text-xs text-[var(--muted)]">{isArabic ? `مسودة ${versions.draft} • منشور ${versions.published}` : `Draft ${versions.draft} • Published ${versions.published}`}</span><button type="button" onClick={() => submit("save")} disabled={status === "saving" || status === "publishing"} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-white/10 px-4 py-2 text-sm font-semibold text-[var(--cream)] disabled:opacity-50"><Save className="h-4 w-4" aria-hidden="true" />{isArabic ? "حفظ مسودة" : "Save draft"}</button><button type="button" onClick={() => submit("publish")} disabled={status === "saving" || status === "publishing"} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-[var(--gold)] px-4 py-2 text-sm font-semibold text-black disabled:opacity-50"><Send className="h-4 w-4" aria-hidden="true" />{isArabic ? "نشر الآن" : "Publish now"}</button></div></div>
    <div className="salora-scroll-strip mt-4" role="tablist" aria-label={isArabic ? "أقسام استوديو التصميم" : "Design studio sections"}>{tabs.map(({ id, ar, en, icon: Icon }) => <button key={id} type="button" role="tab" aria-selected={tab === id} onClick={() => setTab(id)} className={`inline-flex min-h-11 shrink-0 items-center gap-2 rounded-xl px-3 py-2 text-sm font-semibold ${tab === id ? "bg-[var(--gold)] text-black" : "border border-white/10 text-[var(--muted)] hover:border-white/25 hover:text-[var(--cream)]"}`}><Icon className="h-4 w-4" aria-hidden="true" />{isArabic ? ar : en}</button>)}</div>
    {message ? <p className={`mt-3 rounded-xl border px-3 py-2 text-sm ${status === "error" ? "border-red-400/20 bg-red-400/10 text-red-200" : "border-emerald-400/20 bg-emerald-400/10 text-emerald-200"}`}>{message}</p> : null}
    <div className="mt-5 grid gap-6 xl:grid-cols-[minmax(0,1fr)_minmax(360px,.9fr)]">
      <div className="grid content-start gap-4">
        {tab === "menu" ? <><div className="grid gap-3 sm:grid-cols-3"><label className="grid gap-2 text-sm text-[var(--muted)]">{isArabic ? "التخطيط" : "Layout"}<select value={config.menu.layout} onChange={(e) => update("menu", { ...config.menu, layout: e.target.value as ExperienceConfiguration["menu"]["layout"] })} className={fieldClass}><option value="grid">Grid</option><option value="list">List</option><option value="editorial">Editorial</option></select></label><label className="grid gap-2 text-sm text-[var(--muted)]">{isArabic ? "عدد الأعمدة" : "Columns"}<select value={config.menu.columns} onChange={(e) => update("menu", { ...config.menu, columns: Number(e.target.value) as 2 | 3 | 4 })} className={fieldClass}><option>2</option><option>3</option><option>4</option></select></label><label className="grid gap-2 text-sm text-[var(--muted)]">{isArabic ? "نسبة الصورة" : "Image ratio"}<select value={config.menu.cardRatio} onChange={(e) => update("menu", { ...config.menu, cardRatio: e.target.value as ExperienceConfiguration["menu"]["cardRatio"] })} className={fieldClass}><option value="landscape">16:10</option><option value="square">1:1</option><option value="portrait">4:5</option></select></label></div><div className="grid gap-3 sm:grid-cols-2"><Toggle label={isArabic ? "إظهار الصور" : "Show images"} checked={config.menu.showImages} onChange={(value) => update("menu", { ...config.menu, showImages: value })} /><Toggle label={isArabic ? "إظهار الوصف" : "Show descriptions"} checked={config.menu.showDescriptions} onChange={(value) => update("menu", { ...config.menu, showDescriptions: value })} /><Toggle label={isArabic ? "إظهار البحث" : "Show search"} checked={config.menu.showSearch} onChange={(value) => update("menu", { ...config.menu, showSearch: value })} /><Toggle label={isArabic ? "إظهار الفئات" : "Show categories"} checked={config.menu.showCategories} onChange={(value) => update("menu", { ...config.menu, showCategories: value })} /></div></> : null}
        {tab === "theme" ? <><div className="grid gap-3 sm:grid-cols-2">{(["primaryColor", "backgroundColor", "surfaceColor", "textColor", "mutedColor"] as const).map((key) => <label key={key} className="flex items-center gap-3 rounded-xl border border-white/10 bg-white/[0.035] p-3 text-sm text-[var(--muted)]"><input type="color" value={config.theme[key]} onChange={(e) => update("theme", { ...config.theme, [key]: e.target.value })} className="h-10 w-12 rounded border-0 bg-transparent" /><span>{key}</span><code className="ms-auto text-xs">{config.theme[key]}</code></label>)}</div><label className="grid gap-2 text-sm text-[var(--muted)]">{isArabic ? "استدارة البطاقات" : "Corner radius"}<input type="range" min="0" max="40" value={config.theme.borderRadius} onChange={(e) => update("theme", { ...config.theme, borderRadius: Number(e.target.value) })} /><span>{config.theme.borderRadius}px</span></label><label className="grid gap-2 text-sm text-[var(--muted)]">{isArabic ? "الخط" : "Font"}<select value={config.theme.fontFamily} onChange={(e) => update("theme", { ...config.theme, fontFamily: e.target.value as ExperienceConfiguration["theme"]["fontFamily"] })} className={fieldClass}><option value="sans">Sans</option><option value="serif">Serif</option><option value="modern">Modern</option></select></label></> : null}
        {tab === "surfaces" ? <><div className="grid gap-3 sm:grid-cols-2"><TextField label={isArabic ? "عنوان عربي" : "Arabic title"} value={config.site.heroTitleAr} onChange={(value) => update("site", { ...config.site, heroTitleAr: value })} /><TextField label={isArabic ? "عنوان إنجليزي" : "English title"} value={config.site.heroTitleEn} onChange={(value) => update("site", { ...config.site, heroTitleEn: value })} /><TextField multiline label={isArabic ? "وصف عربي" : "Arabic subtitle"} value={config.site.heroSubtitleAr} onChange={(value) => update("site", { ...config.site, heroSubtitleAr: value })} /><TextField multiline label={isArabic ? "وصف إنجليزي" : "English subtitle"} value={config.site.heroSubtitleEn} onChange={(value) => update("site", { ...config.site, heroSubtitleEn: value })} /><TextField label={isArabic ? "رابط الشعار HTTPS" : "HTTPS logo URL"} value={config.site.logoUrl} onChange={(value) => update("site", { ...config.site, logoUrl: value })} /><Toggle label={isArabic ? "إظهار شريط الإعلان" : "Show announcement"} checked={config.site.showAnnouncement} onChange={(value) => update("site", { ...config.site, showAnnouncement: value })} /><TextField label={isArabic ? "الإعلان بالعربية" : "Arabic announcement"} value={config.site.announcementAr} onChange={(value) => update("site", { ...config.site, announcementAr: value })} /><TextField label={isArabic ? "الإعلان بالإنجليزية" : "English announcement"} value={config.site.announcementEn} onChange={(value) => update("site", { ...config.site, announcementEn: value })} /></div><div className="grid gap-3 sm:grid-cols-2"><Toggle label={isArabic ? "الطلب من التطبيق" : "App ordering"} checked={config.app.showOrdering} onChange={(value) => update("app", { ...config.app, showOrdering: value })} /><Toggle label={isArabic ? "توصيات التطبيق" : "App recommendations"} checked={config.app.showRecommendations} onChange={(value) => update("app", { ...config.app, showRecommendations: value })} /><Toggle label={isArabic ? "بطاقات تطبيق مدمجة" : "Compact app cards"} checked={config.app.compactCards} onChange={(value) => update("app", { ...config.app, compactCards: value })} /></div></> : null}
        {tab === "banners" ? <><button type="button" onClick={addBanner} className="inline-flex w-fit items-center gap-2 rounded-xl bg-[var(--gold)] px-4 py-2 text-sm font-semibold text-black"><Plus className="h-4 w-4" />{isArabic ? "إضافة بنر" : "Add banner"}</button>{config.banners.map((banner) => <div key={banner.id} className="grid gap-3 rounded-xl border border-white/10 bg-white/[0.035] p-4 sm:grid-cols-2"><TextField label="العنوان العربي" value={banner.titleAr} onChange={(value) => updateBanner(banner.id, { titleAr: value })} /><TextField label="English title" value={banner.titleEn} onChange={(value) => updateBanner(banner.id, { titleEn: value })} /><TextField label={isArabic ? "رابط الصورة HTTPS" : "HTTPS image URL"} value={banner.imageUrl} onChange={(value) => updateBanner(banner.id, { imageUrl: value })} /><TextField label={isArabic ? "رابط الوجهة" : "Destination"} value={banner.linkUrl} onChange={(value) => updateBanner(banner.id, { linkUrl: value })} /><label className="grid gap-2 text-sm text-[var(--muted)]">{isArabic ? "المكان" : "Placement"}<select value={banner.placement} onChange={(e) => updateBanner(banner.id, { placement: e.target.value as ExperienceBanner["placement"] })} className={fieldClass}><option value="both">Both</option><option value="menu">Menu</option><option value="home">Home</option></select></label><div className="flex items-end gap-2"><Toggle label={isArabic ? "نشط" : "Active"} checked={banner.active} onChange={(value) => updateBanner(banner.id, { active: value })} /><button type="button" aria-label={isArabic ? "حذف البنر" : "Delete banner"} onClick={() => update("banners", config.banners.filter((item) => item.id !== banner.id))} className="rounded-xl border border-red-400/20 p-3 text-red-300"><Trash2 className="h-4 w-4" /></button></div></div>)}</> : null}
        {tab === "history" ? <div className="grid gap-3"><p className="text-sm text-[var(--muted)]">{isArabic ? `المسودة ${versions.draft} • المنشور ${versions.published}` : `Draft ${versions.draft} • Published ${versions.published}`}</p>{history.length ? history.map((revision) => <div key={revision.id} className="flex flex-col gap-3 rounded-xl border border-white/10 bg-white/[0.035] p-4 sm:flex-row sm:items-center sm:justify-between"><div><strong className="text-sm text-[var(--cream)]">{revision.action}</strong><p className="mt-1 text-xs text-[var(--muted)]">{new Date(revision.createdAt).toLocaleString(isArabic ? "ar-OM" : "en-GB")}</p></div><button type="button" onClick={() => rollback(revision.id)} className="inline-flex items-center gap-2 rounded-xl border border-white/10 px-3 py-2 text-xs font-semibold"><RotateCcw className="h-4 w-4" />{isArabic ? "استرجاع ونشر" : "Restore & publish"}</button></div>) : <p className="text-sm text-[var(--muted)]">{isArabic ? "لا توجد إصدارات منشورة بعد." : "No published revisions yet."}</p>}</div> : null}
      </div>
      <div className="xl:sticky xl:top-24 xl:self-start"><p className="mb-2 text-xs font-semibold uppercase tracking-[0.2em] text-[var(--muted)]">{isArabic ? "معاينة مباشرة" : "Live preview"}</p><Preview config={config} isArabic={isArabic} /></div>
    </div>
  </section>;
}
