"use client";
import { useEffect,useMemo,useState } from "react";
import { DashboardCard } from "@/components/dashboard/DashboardCard";
import { controlTowerGet, controlTowerPost } from "@/lib/control-tower/client";
import { useControlTowerLocale } from "./ControlTowerLocale";

type Row={customerId:string;displayName:string|null;visits:number;lifetimeSpend:number;averageOrderValue:number;daysSinceLastVisit:number|null;loyaltyBalance:number;favoriteCategory:string|null;lifecycle:"NEW"|"REGULAR"|"VIP"|"AT_RISK"|"DORMANT";lifecycleReason:string};
type Payload={generatedAt:string;counts:Record<string,number>;customers:Row[]};
type LedgerEntry={id:string;type:string;points:number;reason:string};
type Reward={id:string;name:string;pointsCost:number};
type Detail={account:{points:number;ledger:LedgerEntry[]}|null;rewards:Reward[]};

export function HarmonyCustomerWorkspace(){
 const {isArabic}=useControlTowerLocale(); const [data,setData]=useState<Payload|null>(null); const [error,setError]=useState(""); const [segment,setSegment]=useState("ALL"); const [selected,setSelected]=useState<Row|null>(null); const [detail,setDetail]=useState<Detail|null>(null); const [points,setPoints]=useState(""); const [reason,setReason]=useState(""); const [notice,setNotice]=useState(""); const [busy,setBusy]=useState(false);
 useEffect(()=>{void controlTowerGet<Payload>("/api/intelligence/customers/harmony").then(r=>{if(r.status==="success"&&r.data)setData(r.data);else setError(r.message??"Unable to load Harmony intelligence.");});},[]);
 useEffect(()=>{if(!selected)return;void controlTowerGet<Detail>(`/api/control-tower/harmony?customerId=${encodeURIComponent(selected.customerId)}`).then(r=>{if(r.status==="success"&&r.data)setDetail(r.data);});},[selected]);
 async function mutate(payload:Record<string,unknown>){if(!selected)return;setBusy(true);setNotice("");const result=await controlTowerPost("/api/control-tower/harmony",{customerId:selected.customerId,reason,...payload},{"Idempotency-Key":crypto.randomUUID()});setBusy(false);if(result.status!=="success"){setNotice(result.message??"Mutation failed.");return;}setNotice(isArabic?"تم تنفيذ العملية وتسجيلها.":"Mutation applied and audited.");const refreshed=await controlTowerGet<Detail>(`/api/control-tower/harmony?customerId=${encodeURIComponent(selected.customerId)}`);if(refreshed.status==="success"&&refreshed.data)setDetail(refreshed.data);}
 const rows=useMemo(()=>data?.customers.filter(r=>segment==="ALL"||r.lifecycle===segment)??[],[data,segment]);
 const labels:Record<string,string>={ALL:isArabic?"الكل":"All",NEW:isArabic?"جدد":"New",REGULAR:isArabic?"منتظمون":"Regular",VIP:"VIP",AT_RISK:isArabic?"معرضون للفقد":"At risk",DORMANT:isArabic?"خاملون":"Dormant"};
 return <div className="grid gap-4 sm:gap-5">\n  <section className="overflow-hidden rounded-2xl border border-[var(--border-gold)] bg-[linear-gradient(135deg,rgba(197,160,86,.12),rgba(255,255,255,.025))] p-4 sm:p-5"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-[var(--gold-soft)]">Harmony Rewards</p><h2 className="mt-1 text-xl font-semibold">{isArabic?"الولاء والمكافآت":"Loyalty & Rewards"}</h2><p className="mt-1 max-w-2xl text-sm leading-6 text-[var(--muted)]">{isArabic?"إدارة نقاط العملاء وشرائح الولاء والمكافآت من مساحة واحدة.":"Manage customer points, loyalty segments and rewards from one workspace."}</p></div><div className="rounded-xl border border-[var(--border-gold)] bg-black/20 px-3 py-2 text-center"><span className="block text-[10px] text-[var(--muted)]">{isArabic?"العملاء":"Customers"}</span><strong className="text-xl">{data?.customers.length??0}</strong></div></div></section>
  <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 xl:grid-cols-5">{["NEW","REGULAR","VIP","AT_RISK","DORMANT"].map(k=><DashboardCard key={k} title={labels[k]} eyebrow="Harmony"><p className="text-2xl font-semibold sm:text-3xl">{data?.counts[k]??0}</p></DashboardCard>)}</div>
  <DashboardCard title={isArabic?"عملاء Harmony":"Harmony Customers"} eyebrow={isArabic?"ذكاء قابل للتفسير":"Explainable intelligence"}>
   <div className="salora-scroll-strip mb-4 flex gap-2 overflow-x-auto pb-1">{Object.keys(labels).map(k=><button key={k} onClick={()=>setSegment(k)} className={`min-h-11 shrink-0 rounded-xl border px-3 text-sm ${segment===k?"border-[var(--gold)] bg-[var(--gold)]/10":"border-white/10"}`}>{labels[k]}</button>)}</div>
   {error?<p className="text-sm text-red-200">{error}</p>:null}
   {!data&&!error?<p className="text-sm text-[var(--muted)]">{isArabic?"جارٍ تحميل البيانات...":"Loading governed customer data..."}</p>:null}
   <div className="grid gap-2 md:hidden">{rows.map(r=><button key={r.customerId} onClick={()=>{setDetail(null);setSelected(r);}} className="rounded-xl border border-white/10 bg-white/[.025] p-3 text-start"><div className="flex items-center justify-between gap-3"><strong className="truncate">{r.displayName||r.customerId.slice(0,8)}</strong><span className="shrink-0 rounded-full border border-[var(--border-gold)] px-2 py-1 text-[10px] text-[var(--gold-soft)]">{labels[r.lifecycle]}</span></div><div className="mt-3 grid grid-cols-3 gap-2 text-xs"><span><b className="block text-base">{r.visits}</b><small className="text-[var(--muted)]">{isArabic?"زيارة":"Visits"}</small></span><span><b className="block text-base">{r.loyaltyBalance}</b><small className="text-[var(--muted)]">{isArabic?"نقطة":"Points"}</small></span><span><b className="block text-base">{r.lifetimeSpend.toFixed(3)}</b><small className="text-[var(--muted)]">OMR</small></span></div></button>)}</div><div className="hidden overflow-x-auto md:block"><table className="w-full min-w-[760px] text-start text-sm"><thead><tr className="border-b border-white/10 text-[var(--muted)]">{[isArabic?"العميل":"Customer",isArabic?"الشريحة":"Segment",isArabic?"الزيارات":"Visits",isArabic?"الإنفاق":"Spend",isArabic?"النقاط":"Points",isArabic?"التفضيل":"Affinity",isArabic?"السبب":"Reason"].map(h=><th key={h} className="px-3 py-3 text-start font-medium">{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.customerId} className="border-b border-white/5"><td className="px-3 py-3"><button className="underline-offset-4 hover:underline" onClick={()=>{setDetail(null);setSelected(r);}}>{r.displayName||r.customerId.slice(0,8)}</button></td><td className="px-3 py-3">{labels[r.lifecycle]}</td><td className="px-3 py-3">{r.visits}</td><td className="px-3 py-3">{r.lifetimeSpend.toFixed(3)} OMR</td><td className="px-3 py-3">{r.loyaltyBalance}</td><td className="px-3 py-3">{r.favoriteCategory??"—"}</td><td className="max-w-xs px-3 py-3 text-[var(--muted)]">{r.lifecycleReason}</td></tr>)}</tbody></table></div>
  </DashboardCard>
  {selected?<DashboardCard title={selected.displayName||selected.customerId.slice(0,8)} eyebrow={isArabic?"تفاصيل Harmony":"Harmony detail"}><div className="grid gap-4 lg:grid-cols-2"><div><p className="mb-2 font-medium">{isArabic?"سجل النقاط":"Ledger timeline"}</p><div className="grid gap-2">{detail?.account?.ledger?.map((e)=><div key={e.id} className="rounded-xl border border-white/10 p-3 text-sm"><div className="flex justify-between"><span>{e.type}</span><strong>{e.points>0?"+":""}{e.points}</strong></div><p className="text-[var(--muted)]">{e.reason}</p>{e.type!=="REVERSAL"?<button disabled={busy||reason.trim().length<5} onClick={()=>void mutate({action:"reverse",entryId:e.id})} className="mt-2 min-h-11 rounded-lg border border-white/10 px-3 disabled:opacity-40">{isArabic?"عكس القيد":"Reverse"}</button>:null}</div>)??<p className="text-sm text-[var(--muted)]">—</p>}</div></div><div><p className="mb-2 font-medium">{isArabic?"المكافآت المتاحة":"Available rewards"}</p><div className="grid gap-2">{detail?.rewards?.map((r)=><div key={r.id} className="rounded-xl border border-white/10 p-3 text-sm"><div className="flex justify-between"><span>{r.name}</span><strong>{r.pointsCost} pts</strong></div><button disabled={busy||reason.trim().length<5||(detail?.account?.points??0)<r.pointsCost} onClick={()=>void mutate({action:"redeem",rewardId:r.id})} className="mt-2 min-h-11 rounded-lg border border-white/10 px-3 disabled:opacity-40">{isArabic?"استبدال":"Redeem"}</button></div>)??<p className="text-sm text-[var(--muted)]">—</p>}</div><div className="mt-4 grid gap-2"><input aria-label={isArabic?"سبب عملية Harmony":"Harmony mutation reason"} value={reason} onChange={e=>setReason(e.target.value)} placeholder={isArabic?"سبب العملية (5 أحرف على الأقل)":"Reason (minimum 5 characters)"} className="min-h-11 rounded-xl border border-white/10 bg-transparent px-3"/><div className="flex gap-2"><input aria-label={isArabic?"تعديل نقاط Harmony":"Harmony points adjustment"} type="number" value={points} onChange={e=>setPoints(e.target.value)} placeholder={isArabic?"تعديل النقاط":"Points adjustment"} className="min-h-11 min-w-0 flex-1 rounded-xl border border-white/10 bg-transparent px-3"/><button disabled={busy||reason.trim().length<5||!Number.isInteger(Number(points))||Number(points)===0} onClick={()=>void mutate({action:"adjust",points:Number(points)})} className="min-h-11 rounded-xl border border-[var(--gold)] px-4 disabled:opacity-40">{isArabic?"تطبيق":"Apply"}</button></div>{notice?<p className="text-xs text-[var(--muted)]">{notice}</p>:null}</div><p className="mt-4 text-xs text-[var(--muted)]">{isArabic?"التعديلات والعكس محمية بصلاحيات المدير وسجل التدقيق ومفتاح منع التكرار.":"Adjustments and reversals are protected by manager RBAC, audit logging, and idempotency."}</p></div></div></DashboardCard>:null}
 </div>;
}
