"use client";

import Image from "next/image";
import { useEffect, useMemo, useState } from "react";
import { controlTowerGet, controlTowerPost } from "@/lib/control-tower/client";
import type { RenderJob } from "@/lib/media-studio/contracts";

type ProductImage = { id: string; publicUrl?: string | null; altText?: string | null; isPrimary?: boolean };
type Product = { id: string; slug: string; name: string; nameAr?: string | null; nameEn?: string | null; status: string; basePrice: string | number; images?: ProductImage[] };
type Scene = { id: string; title: string; durationSeconds: number; direction: string; assetIds: string[] };
const formats = [{id:"reel",label:"ريل 9:16",ratio:"1080×1920"},{id:"story",label:"ستوري 9:16",ratio:"1080×1920"},{id:"feed",label:"منشور 4:5",ratio:"1080×1350"},{id:"landscape",label:"أفقي 16:9",ratio:"1920×1080"}] as const;
const goals = [{id:"product",label:"إبراز منتج"},{id:"offer",label:"عرض ترويجي"},{id:"launch",label:"إطلاق جديد"},{id:"brand",label:"فيلم العلامة"}] as const;
const initialScenes: Scene[] = [{id:"hook",title:"الافتتاحية",durationSeconds:3,direction:"لقطة افتتاحية قوية للمنتج بحركة سينمائية هادئة.",assetIds:[]},{id:"detail",title:"تفاصيل المنتج",durationSeconds:7,direction:"إظهار الاسم والملمس والتفاصيل البصرية بوضوح.",assetIds:[]},{id:"brand",title:"ختام سالورا",durationSeconds:5,direction:"ختام فاخر مع SALORA و Taste the Harmony.",assetIds:[]}];

export function MediaStudioWorkspace() {
  const [products,setProducts]=useState<Product[]>([]); const [productSlug,setProductSlug]=useState("");
  const [format,setFormat]=useState<(typeof formats)[number]["id"]>("reel"); const [goal,setGoal]=useState<(typeof goals)[number]["id"]>("product");
  const [prompt,setPrompt]=useState("أنشئ فيديو سينمائي فاخر لسالورا باستخدام هوية العلامة وصور المنتج المعتمدة.");
  const [scenes,setScenes]=useState<Scene[]>(initialScenes); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [message,setMessage]=useState(""); const [job,setJob]=useState<RenderJob|null>(null); const [aiSuggestion,setAiSuggestion]=useState("");
  useEffect(()=>{let active=true;void Promise.all([controlTowerGet<Product[]>("/api/control-tower/simple-launch/products?limit=100&offset=0"),controlTowerGet<Product[]>("/api/control-tower/simple-launch/products?limit=100&offset=100")]).then(([a,b])=>{if(!active)return;const merged=[...new Map([...(a.data??[]),...(b.data??[])].map(p=>[p.id,p])).values()].filter(p=>p.status==="ACTIVE"&&p.images?.some(i=>i.publicUrl));setProducts(merged);setProductSlug(c=>c||merged[0]?.slug||"");if(a.status==="error"&&b.status==="error")setMessage(a.message??b.message??"تعذر تحميل الكتالوج.");setLoading(false);});return()=>{active=false};},[]);
  const product=useMemo(()=>products.find(p=>p.slug===productSlug),[products,productSlug]); const selectedFormat=formats.find(f=>f.id===format)??formats[0]; const assets=product?.images?.filter(i=>i.publicUrl)??[]; const selectedAssetIds=new Set(scenes.flatMap(s=>s.assetIds)); const hero=assets.find(a=>selectedAssetIds.has(a.id))??assets.find(a=>a.isPrimary)??assets[0]; const duration=scenes.reduce((n,s)=>n+s.durationSeconds,0);
  function toggleAsset(id:string){setScenes(c=>c.map((s,i)=>i===0?{...s,assetIds:s.assetIds.includes(id)?s.assetIds.filter(x=>x!==id):[...s.assetIds,id]}:s));}
  function updateScene(index:number,patch:Partial<Scene>){setScenes(c=>c.map((s,i)=>i===index?{...s,...patch}:s));}
  function addScene(){if(scenes.length<12)setScenes(c=>[...c,{id:`scene-${Date.now()}`,title:"مشهد جديد",durationSeconds:4,direction:"صف اللقطة البصرية.",assetIds:[]}]);}
  async function askAi(){if(!product)return;setBusy(true);setMessage("المخرج الإبداعي يعمل الآن…");const r=await controlTowerPost<{suggestion:string}>("/api/control-tower/media-studio/ai-director",{productSlug:product.slug,goal,format,creativeDirection:prompt,locale:"ar"});if(r.status==="success"&&r.data?.suggestion){setAiSuggestion(r.data.suggestion);setMessage("تم إنشاء اقتراح إبداعي بالذكاء الاصطناعي للمراجعة البشرية.");}else setMessage(r.message??"تعذر تشغيل المخرج الذكي.");setBusy(false);}
  async function createJob(){if(!product)return;setBusy(true);setMessage("جاري حفظ مشروع الرندر…");const r=await controlTowerPost<{job:RenderJob}>("/api/control-tower/media-studio/render-jobs",{productSlug:product.slug,goal,format,creativeDirection:prompt,scenes});if(r.status==="success"&&r.data?.job){setJob(r.data.job);setMessage("تم إنشاء RenderJob حقيقي وحفظه مع Audit Trail.");}else setMessage(r.message??"فشل إنشاء مشروع الرندر.");setBusy(false);}
  async function review(decision:"APPROVED"|"REJECTED"){if(!job)return;setBusy(true);const r=await controlTowerPost<{state:RenderJob["state"]}>(`/api/control-tower/media-studio/render-jobs/${job.id}/review`,{decision,notes:decision==="APPROVED"?"Approved by SALORA operator from Media Studio.":"Rejected by SALORA operator from Media Studio."});if(r.status==="success"&&r.data){setJob({...job,state:r.data.state});setMessage(decision==="APPROVED"?"تمت الموافقة البشرية وتسجيلها في سجل التدقيق.":"تم الرفض وتسجيل القرار.");}else setMessage(r.message??"تعذر تسجيل المراجعة.");setBusy(false);}
  return <div dir="rtl" className="grid gap-5 xl:grid-cols-[minmax(0,1.25fr)_minmax(320px,.75fr)]">
    <section className="space-y-6 rounded-3xl border border-[var(--border-subtle)] bg-[var(--surface)] p-4 sm:p-6">
      <div><p className="text-xs font-semibold tracking-[.12em] text-[var(--gold-soft)]">SALORA AI MEDIA STUDIO · P77-D</p><h2 className="mt-2 text-2xl font-semibold text-[var(--cream)]">من الفكرة إلى فيديو جاهز للمراجعة</h2><p className="mt-2 text-sm leading-7 text-[var(--muted)]">كتالوج حي، مخرج إبداعي بالذكاء الاصطناعي، Storyboard، RenderJob محفوظ، وسجل تدقيق مع موافقة بشرية إلزامية.</p></div>
      <div className="grid gap-4 md:grid-cols-3"><label className="grid gap-2 text-sm"><span>المنتج</span><select disabled={loading} value={productSlug} onChange={e=>{setProductSlug(e.target.value);setScenes(initialScenes);setJob(null)}} className="min-h-12 rounded-xl border border-[var(--border-subtle)] bg-black/20 px-3"><option value="">اختر المنتج</option>{products.map(p=><option key={p.id} value={p.slug}>{p.nameAr||p.nameEn||p.name}</option>)}</select></label><label className="grid gap-2 text-sm"><span>الهدف</span><select value={goal} onChange={e=>setGoal(e.target.value as typeof goal)} className="min-h-12 rounded-xl border border-[var(--border-subtle)] bg-black/20 px-3">{goals.map(g=><option key={g.id} value={g.id}>{g.label}</option>)}</select></label><label className="grid gap-2 text-sm"><span>المقاس</span><select value={format} onChange={e=>setFormat(e.target.value as typeof format)} className="min-h-12 rounded-xl border border-[var(--border-subtle)] bg-black/20 px-3">{formats.map(f=><option key={f.id} value={f.id}>{f.label}</option>)}</select></label></div>
      <label className="grid gap-2 text-sm"><span>التوجيه الإبداعي</span><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} rows={3} className="rounded-2xl border border-[var(--border-subtle)] bg-black/20 px-4 py-3"/></label>
      <button type="button" disabled={!product||busy} onClick={()=>void askAi()} className="min-h-12 w-full rounded-xl border border-[var(--border-gold)] px-5 font-semibold text-[var(--gold-soft)] disabled:opacity-50">✦ إنشاء Storyboard بالذكاء الاصطناعي</button>
      {aiSuggestion?<div className="whitespace-pre-wrap rounded-2xl border border-[var(--border-gold)] bg-[var(--gold)]/[.05] p-4 text-sm leading-7"><strong>اقتراح المخرج الذكي</strong><p className="mt-2 text-[var(--muted)]">{aiSuggestion}</p></div>:null}
      <div><div className="flex items-end justify-between"><div><h3 className="font-semibold">الوسائط المعتمدة</h3><p className="text-xs text-[var(--muted)]">اختر صورة البطل للمشهد الأول.</p></div><span className="text-xs text-[var(--muted)]">{assets.length}</span></div><div className="mt-3 grid grid-cols-3 gap-3 sm:grid-cols-5">{assets.map(a=><button type="button" key={a.id} onClick={()=>toggleAsset(a.id)} className={`relative aspect-square overflow-hidden rounded-2xl border ${selectedAssetIds.has(a.id)?"border-[var(--gold)]":"border-[var(--border-subtle)]"}`}>{a.publicUrl?<Image src={a.publicUrl} alt={a.altText||product?.name||"SALORA"} fill unoptimized className="object-cover"/>:null}</button>)}</div></div>
      <div><div className="flex items-center justify-between"><div><h3 className="font-semibold">Storyboard</h3><p className="text-xs text-[var(--muted)]">{scenes.length} مشاهد · {duration} ثانية</p></div><button type="button" onClick={addScene} className="min-h-11 rounded-xl border border-[var(--border-gold)] px-4">+ مشهد</button></div><div className="mt-3 space-y-3">{scenes.map((s,i)=><div key={s.id} className="grid gap-3 rounded-2xl border border-[var(--border-subtle)] bg-white/[.02] p-4 sm:grid-cols-[1fr_100px]"><div className="space-y-2"><input value={s.title} onChange={e=>updateScene(i,{title:e.target.value})} className="w-full rounded-lg bg-black/20 px-3 py-2 font-semibold"/><textarea value={s.direction} onChange={e=>updateScene(i,{direction:e.target.value})} rows={2} className="w-full rounded-lg bg-black/20 px-3 py-2 text-sm"/></div><label className="text-xs text-[var(--muted)]">الثواني<input type="number" min={1} max={12} value={s.durationSeconds} onChange={e=>updateScene(i,{durationSeconds:Math.max(1,Math.min(12,Number(e.target.value)||1))})} className="mt-2 w-full rounded-lg bg-black/20 px-3 py-2 text-[var(--cream)]"/></label></div>)}</div></div>
      <button type="button" disabled={!product||!assets.length||duration>60||busy} onClick={()=>void createJob()} className="min-h-12 w-full rounded-xl bg-[var(--gold)] px-5 font-semibold text-[#17120a] disabled:opacity-50">إنشاء مشروع الرندر</button>{message?<p role="status" className="text-sm leading-6 text-[var(--muted)]">{message}</p>:null}
    </section>
    <aside className="space-y-4"><div className="rounded-3xl border border-[var(--border-gold)] bg-[var(--surface)] p-4"><div dir="ltr" className="flex justify-between text-xs text-[var(--muted)]"><span>{selectedFormat.label}</span><span>{selectedFormat.ratio}</span></div><div className="relative mx-auto mt-4 aspect-[9/16] max-h-[520px] overflow-hidden rounded-2xl bg-black">{hero?.publicUrl?<Image src={hero.publicUrl} alt={hero.altText||product?.name||"SALORA preview"} fill unoptimized className="object-cover opacity-75"/>:null}<div className="absolute inset-0 bg-gradient-to-t from-black via-black/10 to-transparent"/><div className="absolute inset-x-5 bottom-6"><p dir="ltr" className="text-xs font-semibold tracking-[.18em] text-[var(--gold-soft)]">TASTE THE HARMONY</p><h3 className="mt-2 text-2xl font-semibold">{product?.nameAr||product?.nameEn||"SALORA"}</h3><p className="mt-2 text-sm text-white/70">SaloraProductPreview · {duration}s</p></div></div></div>{job?<div className="rounded-3xl border border-emerald-300/20 bg-emerald-300/[.05] p-5 text-sm"><strong>RenderJob محفوظ</strong><p dir="ltr" className="mt-2 break-all text-[var(--muted)]">{job.id} · {job.state}</p><div className="mt-4 grid grid-cols-2 gap-2"><button disabled={busy||job.state==="APPROVED"} onClick={()=>void review("APPROVED")} className="min-h-11 rounded-xl bg-emerald-400/15 px-3 font-semibold text-emerald-200 disabled:opacity-40">اعتماد</button><button disabled={busy} onClick={()=>void review("REJECTED")} className="min-h-11 rounded-xl bg-red-400/10 px-3 font-semibold text-red-200 disabled:opacity-40">رفض</button></div></div>:null}<div className="rounded-3xl border border-[var(--border-subtle)] bg-[var(--surface)] p-5 text-sm leading-7 text-[var(--muted)]">النشر الخارجي لا يتم تلقائيًا. الرندر النهائي والنشر يظلان خلف موافقة بشرية وصلاحيات الخادم وسجل التدقيق.</div></aside>
  </div>;
}
